services:
  WorkFlow:
    build: .
    container_name: WorkFlow
    ports:
      - "8004:8004"
    env_file: 
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: e-services-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
