# Generated by Django 5.1.3 on 2025-04-15 06:08

import django.contrib.auth.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizational_structure", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "employment_number",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Employment Number"
                    ),
                ),
                (
                    "second_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Second Number",
                    ),
                ),
                (
                    "Third_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Third Number",
                    ),
                ),
                (
                    "job_title",
                    models.CharField(max_length=200, verbose_name="Job Title"),
                ),
                (
                    "mobile_number",
                    models.CharField(max_length=200, verbose_name="Mobile Number"),
                ),
                (
                    "email",
                    models.CharField(max_length=200, unique=True, verbose_name="Email"),
                ),
                ("address", models.CharField(max_length=500, verbose_name="Address")),
                (
                    "password",
                    models.CharField(
                        default="P@ssw0rd", max_length=128, verbose_name="Password"
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="employee_images/",
                        verbose_name="Profile Image",
                    ),
                ),
                (
                    "positions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="employees",
                        to="organizational_structure.position",
                        verbose_name="Positions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee",
                "verbose_name_plural": "Employees",
                "db_table": "employees",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
