# Generated by Django 5.1.3 on 2025-07-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0002_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflow",
            name="code",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="name_ar",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="name_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
