# Generated by Django 5.1.3 on 2025-08-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0003_alter_workflow_code_alter_workflow_name_ar_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="action",
            name="is_external",
        ),
        migrations.AddField(
            model_name="action",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("external_entity", "External Entity"),
                    ("complete_application", "Complete Application"),
                    ("step", "Step"),
                ],
                default="step",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="action",
            name="status",
            field=models.CharField(
                choices=[
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("rejected", "Rejected"),
                ],
                default="completed",
                max_length=20,
            ),
        ),
    ]
