# Generated by Django 5.1.3 on 2025-08-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0004_remove_action_is_external_action_action_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="step",
            name="link_form",
            field=models.CharField(
                blank=True,
                choices=[("applicant", "Applicant"), ("position", "Position")],
                help_text="Type of form to link: applicant or position",
                max_length=20,
                null=True,
            ),
        ),
    ]
