# Generated by Django 5.1.3 on 2025-08-21 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0005_step_link_form"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="next_step",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actions_to",
                to="engine.step",
            ),
        ),
    ]
